### ISSUE TITLE
How big is KL loss

### ISSUE THREAD

**Issue by Tinyyuumi** [ahottung/CVAE-Opt#1]
KL loss weight is 1e-4, will it lead to a large KL loss, resulting in a poor latent space and affecting the optimization? What is the KL loss of the model?

**Comment by ahottung** [comment]
We evaluate the influence of the KL loss weight in Section 4.3 of the paper. Note that the weight is called beta in the paper. We find that the best search performance can be observed for beta values of 1e-2 and 1e-3 for the TSP and the CVRP, respectively.

**Comment by Tinyyuumi** [comment]
Thanks
